# Generated by Django 5.0.2 on 2024-02-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200, verbose_name='Software Name')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last Updated')),
                ('is_monitored', models.BooleanField(default=False, verbose_name='Is Monitored?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
