# Generated by Django 5.0.2 on 2024-03-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_url_ai_summary_url_human_summary_url_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200, verbose_name='Software Name')),
                ('base_urls', models.TextField(blank=True, help_text='Base URLs', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='software_name',
        ),
        migrations.AddField(
            model_name='url',
            name='software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='comparison.software'),
            preserve_default=False,
        ),
    ]
