# Generated by Django 5.0.2 on 2024-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_software_remove_url_software_name_url_software'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='software_name',
            new_name='name',
        ),
    ]
