# Generated by Django 5.0.2 on 2024-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_url_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='similar_urls',
            field=models.TextField(blank=True, help_text='Other URLs which are different that this page, but have the exact same hash.', null=True, verbose_name='Similar URLs'),
        ),
        migrations.AlterField(
            model_name='url',
            name='ai_summary',
            field=models.TextField(blank=True, editable=False, help_text='Content Summary (AI-Generated)', null=True, verbose_name='AI Summary'),
        ),
        migrations.AlterField(
            model_name='url',
            name='human_summary',
            field=models.TextField(blank=True, help_text='Content Summary (Human Generated)', null=True, verbose_name='Human Summary'),
        ),
    ]
