# Generated by Django 5.0.2 on 2024-03-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0006_url_similar_urls_alter_url_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='content_length',
            field=models.IntegerField(blank=True, editable=False, help_text='Content lenght in MD format, removing all new lines', null=True, verbose_name='Content Length'),
        ),
    ]
