# Generated by Django 5.0.2 on 2024-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_url_content_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='similar_urls',
        ),
        migrations.AddField(
            model_name='software',
            name='exclude_urls',
            field=models.TextField(blank=True, help_text='New-line separated URLs to be excluded from the search', null=True, verbose_name='Exclude URLs'),
        ),
        migrations.AlterField(
            model_name='software',
            name='base_urls',
            field=models.TextField(blank=True, help_text='New-line separated URLs on which the search starts. Each line must contain a URL. It also can contain the base URL which all crawled URLs from this URL should start with to be included in the crawl.', null=True, verbose_name='Base URLs'),
        ),
    ]
