# Generated by Django 5.0.2 on 2024-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0008_remove_url_similar_urls_software_exclude_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='similar_urls',
            field=models.TextField(blank=True, help_text='Other URLs which are different that this page, but have the exact same hash.', null=True, verbose_name='Similar URLs'),
        ),
    ]
